config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :questions do
    member do
      get 'quiz'
      post 'quiz', to: 'questions#check_answer'
    end
  end

  resource :learning_session, only: [:show, :create, :destroy]
end

app/models/question.rb
class Question < ApplicationRecord
  validates :content, presence: true
  validates :answer, presence: true

  attribute :answer, AnswerType.new
  delegate :correct?, to: :answer
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :set_question, only: [:show, :edit, :update, :destroy, :quiz, :check_answer]
  after_action :save_answer_to_learning_session, only: :check_answer, if: -> { current_learning_session.present? }

  before_action :redirect_to_current_quiz, except: :check_answer, if: -> { not completed? }

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def quiz
  end

  def check_answer
    @quiz_result = @question.correct?(quiz_answer_param)
    flash[:quiz_result] = @quiz_result
    flash[:quiz_answer] = quiz_answer_param
    respond_to do |format|
      format.html { redirect_to quiz_question_path(completed: true) }
      format.json { render :quiz, status: :ok, location: @question }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content, :answer)
    end

    def completed?
      params[:completed]
    end

    def quiz_answer_param
      params.require(:quiz).require(:answer)
    end

    def save_answer_to_learning_session
      current_learning_session.answer(@quiz_result)
      session[:learning_session] = current_learning_session.to_h
    end
end

app/views/questions/_form.html.haml
- if @question.errors.any?
  #error_explanation
    %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
    %ul
      - @question.errors.full_messages.each do |message|
        %li= message

.columns
  .column.is-half
    = form_for @question do |f|
      .field
        %label.label= f.label :content
        = f.text_area :content, id: 'mde'
      .field
        %label.label= f.label :answer
        .control
          = f.text_field :answer, value: f.object.answer.to_s, required: true, class: 'input'
      .field
        %button.button.is-primary= 'Save'

  .column.is-half
    .field
      %label.label Preview
    .container
      .card
        .card-content
          #mde-preview.content

app/views/questions/_markdown.html.haml
.content.markdown{'data-text': text}

app/views/questions/edit.html.haml
%h1.title Editing question

= render 'form'

%hr

= link_to 'back to list', questions_path, class: 'button'

app/views/questions/index.html.haml
- if flash[:error]
  .notification.is-danger
    = flash[:error]

%h1.title Questions
= link_to 'Add New Question', new_question_path, class: ['button', 'is-primary']
= link_to 'Start Learning Session', learning_session_path, method: :post, class: ['button', 'is-danger']

%hr

- @questions.each_slice(2) do |questions|
  .tile.is-ancestor
    - questions.each do |question|
      .tile.is-parent.is-6
        .tile.is-child
          .card
            .card-content
              = render 'markdown', text: question.content
            %footer.card-footer
              = link_to 'Quiz', quiz_question_path(question), class: 'card-footer-item'
              = link_to 'Answer', question, class: 'card-footer-item'
              = link_to 'Edit', edit_question_path(question), class: 'card-footer-item'
              = link_to 'Delete', question, method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-footer-item'

app/views/questions/new.html.haml
%h1.title New question

= render 'form'

%hr

= link_to 'Show', @question, class: 'button'

app/views/questions/quiz.html.haml
%h1.title Quiz

- if notice
  %p#notice= notice

.card
  .card-content
    = render 'markdown', text: @question.content

%hr

- if flash[:quiz_answer]
  - if flash[:quiz_result]
    .notification.is-primary
      %p= 'Correct Answer!'
      %p= "Your Answer: #{flash[:quiz_answer]}"
      %p="Correct Answer: #{@question.answer}"
  - else
    .notification.is-danger
      %p= 'Incorrect Answer!'
      %p="Your Answer: #{flash[:quiz_answer]}"
      %p="Correct Answer: #{@question.answer}"

  - if current_learning_session
    = link_to 'Next Quiz', learning_session_path, class: ['button']
  - else
    = link_to 'Try Again', quiz_question_path(@question), class: ['button']
    = link_to 'Back to List', questions_path, class: ['button']
- else
  = form_for :quiz, url: quiz_question_path(@question), method: :post do |f|
    .field
      %label.label= f.label :answer
      .control= f.text_field :answer, value: nil, required: true, class: 'input'

    .field
      %button.button.is-primary= 'Check Answer'

app/views/questions/show.html.haml
%h1.title Question and Answer

- if notice
  .notification.is-primary= notice

.card
  .card-content
    = render 'markdown', text: @question.content
    .container
      %hr
      %p= "Answer: <i>#{@question.answer}</i>".html_safe
  %footer.card-footer
    = link_to 'Edit', edit_question_path(@question), class: 'card-footer-item'
    = link_to 'Delete', @question, method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-footer-item'

%hr
= link_to 'Back to List', questions_path, class: 'button'